epkg install: do not follow symlink in mirror_dir() check
Error: Failed to expose package pbaknz0skh99y3mmdwcs2xxhay5mzbgj__qemu__8.2.0__13.oe2403

Caused by:
    0: Failed to get metadata for /home/wfg/.epkg/store/pbaknz0skh99y3mmdwcs2xxhay5mzbgj__qemu__8.2.0__13.oe2403/fs/usr/bin/qemu-kvm for create_ebin_wrappers
    1: No such file or directory (os error 2)
wfg /c/epkg% ll /home/wfg/.epkg/store/pbaknz0skh99y3mmdwcs2xxhay5mzbgj__qemu__8.2.0__13.oe2403/fs/usr/bin/qemu-kvm
lrwxrwxrwx 1 wfg wfg 21 2024-05-28 16:54 /home/wfg/.epkg/store/pbaknz0skh99y3mmdwcs2xxhay5mzbgj__qemu__8.2.0__13.oe2403/fs/usr/bin/qemu-kvm -> /usr/libexec/qemu-kvm
wfg /c/epkg% ll /usr/libexec/qemu-kvm
ls: cannot access '/usr/libexec/qemu-kvm': No such file or directory

Signed-off-by: Wu Fengguang <wfg@mail.ustc.edu.cn>