deb_repo: install dpkg by default
The install scriptlets depend heavily on dpkg commands, and it need
11.8 MB additional disk space to install dpkg, so the cost is acceptable.

wfg /c/epkg% epkg -e debian install bash
Packages to be freshly installed:
DEPTH       SIZE  PACKAGE
0         1.4 MB  bash__5.2.37-2+b7__amd64
1        71.5 KB  base-files__13.8+deb13u3__amd64
1        90.2 KB  debianutils__5.23.2__amd64
1       311.9 KB  bash-completion__1:2.16.0-7__all
2       657.9 KB  gawk__1:5.2.1-2+b1__amd64
3       712.2 KB  libmpfr6__4.2.2-1__amd64
3        33.6 KB  libsigsegv2__2.14-1+b2__amd64
3       164.9 KB  libreadline8t64__8.2-6__amd64
4        67.7 KB  readline-common__8.2-6__all
4       340.2 KB  libtinfo6__6.5+20250216-2__amd64
4       547.1 KB  libgmp10__2:6.3.0+dfsg-3__amd64
5        48.3 KB  gcc-14-base__14.2.0-19__amd64
6        71.1 KB  libgcc-s1__14.2.0-19__amd64
7       465.6 KB  libunistring5__1.3-2__amd64
8         2.7 MB  libc6__2.41-12+deb13u1__amd64
9       106.5 KB  libidn2-0__2.3.8-2__amd64
Packages to be exposed:
- bash__5.2.37-2+b7__amd64

0 upgraded, 16 newly installed, 0 to remove, 1 to expose, 0 to unexpose.
Need to get 7.8 MB archives.
After this operation, 30.5 MB of additional disk space will be used.

dpkg-query: --show requires at least one package name
/home/wfg/.epkg/store/7xs64v5lzvz4pgbvrqcc22pmtcognah2__libc6__2.41-12+deb13u1__amd64/info/install/pre_install.sh:
line 349: dpkg: command not found
dpkg-query: --listfiles requires at least one package name
/home/wfg/.epkg/store/7xs64v5lzvz4pgbvrqcc22pmtcognah2__libc6__2.41-12+deb13u1__amd64/info/install/pre_install.sh:
line 350: dpkg-divert: command not found
Command '/home/wfg/.epkg/envs/debian/usr/bin/bash' exited with code 127
(no_exit=true, continuing)
/home/wfg/.epkg/store/6iwg43rko2zzfmv6fpo7n6pg6lqyakk5__libreadline8t64__8.2-6__amd64/info/install/pre_install.sh:
line 8: dpkg-divert: command not found
Command '/home/wfg/.epkg/envs/debian/usr/bin/bash' exited with code 127
(no_exit=true, continuing)
/home/wfg/.epkg/store/77cwcjzqbbo2rkrsp26ufjslgg5qnutn__gawk__1:5.2.1-2+b1__amd64/info/install/post_install.sh:
line 4: update-alternatives: command not found
Command '/home/wfg/.epkg/envs/debian/usr/bin/bash' exited with code 127
(no_exit=true, continuing)
/usr/sbin/update-shells: line 77: warning: setlocale: LC_COLLATE: cannot
change locale (C.UTF-8): No such file or directory
/usr/sbin/update-shells: line 85: dpkg-realpath: command not found
/usr/sbin/update-shells: line 85: dpkg-realpath: command not found
/usr/sbin/update-shells: line 85: dpkg-realpath: command not found
/usr/sbin/update-shells: line 85: dpkg-realpath: command not found
/usr/sbin/update-shells: line 85: dpkg-realpath: command not found
error: unexpected argument found
error: unexpected argument found
/usr/sbin/update-shells: line 148: sync: command not found
Command '/home/wfg/.epkg/envs/debian/usr/bin/bash' exited with code 127
(no_exit=true, continuing)
/usr/sbin/update-shells: line 77: warning: setlocale: LC_COLLATE: cannot
change locale (C.UTF-8): No such file or directory
/usr/sbin/update-shells: line 85: dpkg-realpath: command not found
/usr/sbin/update-shells: line 85: dpkg-realpath: command not found
/usr/sbin/update-shells: line 85: dpkg-realpath: command not found
/usr/sbin/update-shells: line 85: dpkg-realpath: command not found
/usr/sbin/update-shells: line 85: dpkg-realpath: command not found
error: unexpected argument found
error: unexpected argument found
/usr/sbin/update-shells: line 148: sync: command not found
Command
'/home/wfg/.epkg/store/askb3fkkbzgvy73vcxesj7dlk4usvsnt__debianutils__5.23.2__amd64/info/deb/postinst'
exited with code 127 (no_exit=true, continuing)
/usr/sbin/update-shells: line 77: warning: setlocale: LC_COLLATE: cannot
change locale (C.UTF-8): No such file or directory
/usr/sbin/update-shells: line 85: dpkg-realpath: command not found
/usr/sbin/update-shells: line 85: dpkg-realpath: command not found
/usr/sbin/update-shells: line 85: dpkg-realpath: command not found
/usr/sbin/update-shells: line 85: dpkg-realpath: command not found
/usr/sbin/update-shells: line 85: dpkg-realpath: command not found
error: unexpected argument found
error: unexpected argument found
/usr/sbin/update-shells: line 148: sync: command not found
Command
'/home/wfg/.epkg/store/askb3fkkbzgvy73vcxesj7dlk4usvsnt__debianutils__5.23.2__amd64/info/deb/postinst'
exited with code 127 (no_exit=true, continuing)
/home/wfg/.epkg/store/k5x4ug46tkevpocklubldxgnz5h7hd4u__base-files__13.8+deb13u3__amd64/info/install/pre_install.sh:
line 51: dpkg-divert: command not found
Command '/home/wfg/.epkg/envs/debian/usr/bin/bash' exited with code 127
(no_exit=true, continuing)
/home/wfg/.epkg/store/k5x4ug46tkevpocklubldxgnz5h7hd4u__base-files__13.8+deb13u3__amd64/info/install/post_install.sh:
line 114: dpkg-divert: command not found
Command '/home/wfg/.epkg/envs/debian/usr/bin/bash' exited with code 127
(no_exit=true, continuing)
/home/wfg/.epkg/store/zxdumxva46bnfb57ma5vfppd426mxnzn__bash__5.2.37-2+b7__amd64/info/install/post_install.sh:
line 10: update-alternatives: command not found
/usr/sbin/update-shells: line 77: warning: setlocale: LC_COLLATE: cannot
change locale (C.UTF-8): No such file or directory
/usr/sbin/update-shells: line 85: dpkg-realpath: command not found
/usr/sbin/update-shells: line 85: dpkg-realpath: command not found
/usr/sbin/update-shells: line 85: dpkg-realpath: command not found
/usr/sbin/update-shells: line 85: dpkg-realpath: command not found
/usr/sbin/update-shells: line 85: dpkg-realpath: command not found
error: unexpected argument found
error: unexpected argument found
/usr/sbin/update-shells: line 148: sync: command not found
Command
'/home/wfg/.epkg/store/askb3fkkbzgvy73vcxesj7dlk4usvsnt__debianutils__5.23.2__amd64/info/deb/postinst'
exited with code 127 (no_exit=true, continuing)

wfg /c/epkg% epkg -e debian install dpkg
Packages to be freshly installed:
DEPTH       SIZE  PACKAGE
0         1.5 MB  dpkg__1.22.21__amd64
1        37.0 KB  libbz2-1.0__1.0.8-6__amd64
1       296.7 KB  libzstd1__1.5.7+dfsg-1__amd64
1        86.8 KB  zlib1g__1:1.3.dfsg+really1.3.1-1+b1__amd64
1       795.9 KB  tar__1.35+dfsg-3.1__amd64
1        35.4 KB  libmd0__1.1.0-2+b1__amd64
1       302.1 KB  liblzma5__5.8.1-1__amd64
2        32.1 KB  libacl1__2.3.2-2+b1__amd64
2        82.7 KB  libselinux1__3.8.1-1__amd64
3       291.5 KB  libpcre2-8-0__10.46-1~deb13u1__amd64
Packages to be exposed:
- dpkg__1.22.21__amd64

0 upgraded, 10 newly installed, 0 to remove, 1 to expose, 0 to unexpose.
Need to get 3.4 MB archives.
After this operation, 11.8 MB of additional disk space will be used.

FYI it'll cost 29MB additional disk space to install coreutils:

wfg /c/epkg% epkg -e debian install coreutils
Packages to be freshly installed:
DEPTH       SIZE  PACKAGE
0         2.9 MB  coreutils__9.7-3__amd64
1        82.7 KB  libselinux1__3.8.1-1__amd64
1        32.1 KB  libacl1__2.3.2-2+b1__amd64
1       442.8 KB  libsystemd0__257.9-1~deb13u1__amd64
1        22.3 KB  libattr1__1:2.5.2-3__amd64
2        28.1 KB  libcap2__1:2.75-10+b3__amd64
2       291.5 KB  libpcre2-8-0__10.46-1~deb13u1__amd64
3         2.3 MB  libssl3t64__3.5.4-1~deb13u2__amd64
4       296.7 KB  libzstd1__1.5.7+dfsg-1__amd64
4       301.1 KB  openssl-provider-legacy__3.5.4-1~deb13u2__amd64
4        86.8 KB  zlib1g__1:1.3.dfsg+really1.3.1-1+b1__amd64
Packages to be exposed:
- coreutils__9.7-3__amd64
0 upgraded, 11 newly installed, 0 to remove, 1 to expose, 0 to unexpose.
Need to get 6.8 MB archives.
After this operation, 29.0 MB of additional disk space will be used.

Signed-off-by: Wu Fengguang <wfg@mail.ustc.edu.cn>