epkg install: fix store dir mv error
Error: Failed to unpack package: /home/wfg/.cache/epkg/downloads/debian/pool/main/o/openssl/libssl3t64_3.5.0-2_amd64.deb

Caused by:
   0: Failed to move package from /home/wfg/.cache/epkg/unpack/8e50e2f3-4954-49e9-9949-111a247c8a56 to /home/wfg/.epkg/store/hd57irbuu6yjbjwhuc54ek42h4h2j75f__libssl3t64__3.5.0-2
   1: No such file or directory (os error 2)

Location:
    src/store.rs:92:10

Signed-off-by: Wu Fengguang <wfg@mail.ustc.edu.cn>