make yaml/json fields optional
wfg /c/epkg% epkg env config get name
Error: Failed to parse YAML from file: /home/wfg/.epkg/config/envs/main.yaml

Caused by:
    missing field `installed_packages`

Signed-off-by: Wu Fengguang <wfg@mail.ustc.edu.cn>