epkg install: fix channel.yaml load error
wfg /c/epkg% epkg install tree
Error: Failed to parse YAML from file: /home/wfg/.epkg/envs/main/etc/epkg/channel.yaml

Caused by:
    missing field `name`

Signed-off-by: Wu Fengguang <wfg@mail.ustc.edu.cn>