feat(environment): Implement package format-specific directory structure
- Load channel yaml to get package format when creating environments
- Modify create_environment_directories to handle different package formats
- Create special lib64 symlinks for Pacman format:
  - /usr/lib64 -> lib
  - /lib64 -> usr/lib
- Fix borrowing conflicts by cloning format before passing to methods
- Reorganize directory creation to ensure etc/epkg exists before writing channel.yaml
- Change create_environment_directories to take immutable self reference

In particular, fix this archlinux issue:

wfg /c/epkg% cp channel/archlinux.yaml /home/wfg/.epkg/envs/main/etc/epkg/channel.yaml
wfg /c/epkg% epkg -v install tree
Retrying https://mirrors.ustc.edu.cn///archlinux/extra/os/x86_64/extra.files.tar.gz (attempt 2/7) after 2s delay...
[00:00:18] [==========] 2.50 MiB/s   (0s) Downloaded /home/wfg/.cache/epkg/downloads/archlinux/extra/os/x86_64/extra.files.tar.gz
[00:00:02] [==========] 0 B/s        (0s) Downloaded /home/wfg/.cache/epkg/downloads/archlinux/multilib/os/x86_64/multilib.files.tar.gz
[00:00:01] [==========] 0 B/s        (0s) Downloaded /home/wfg/.cache/epkg/downloads/archlinux/core/os/x86_64/core.files.tar.gz
Packages to install:
depend_depth package
0            tree__2.2.1-1__x86_64
1            glibc__2.41+r48+g5cb575ca9a3d-1__x86_64
2            tzdata__2025b-1__x86_64
2            filesystem__2025.05.03-1__any
2            linux-api-headers__6.14-1__x86_64
[00:00:02] [==========] 0 B/s        (0s) Downloaded /home/wfg/.cache/epkg/downloads/archlinux/multilib/os/x86_64/multilib.files.tar.gz
[00:00:01] [==========] 0 B/s        (0s) Downloaded /home/wfg/.cache/epkg/downloads/archlinux/core/os/x86_64/core.files.tar.gz
[00:00:04] [==========] 0 B/s        (0s) Downloaded /home/wfg/.cache/epkg/downloads/archlinux/extra/os/x86_64/tree-2.2.1-1-x86_64.pkg.tar.zst
[00:00:00] [==========] 0 B/s        (0s) Downloaded /home/wfg/.cache/epkg/downloads/archlinux/core/os/x86_64/iana-etc-20250502-1-any.pkg.tar.zst
[00:00:02] [==========] 0 B/s        (0s) Downloaded /home/wfg/.cache/epkg/downloads/archlinux/core/os/x86_64/glibc-2.41+r48+g5cb575ca9a3d-1-x86_64.pkg.tar.zst
[00:00:01] [==========] 0 B/s        (0s) Downloaded /home/wfg/.cache/epkg/downloads/archlinux/core/os/x86_64/linux-api-headers-6.14-1-x86_64.pkg.tar.zst
[00:00:03] [==========] 0 B/s        (0s) Downloaded /home/wfg/.cache/epkg/downloads/archlinux/core/os/x86_64/filesystem-2025.05.03-1-any.pkg.tar.zst
[00:00:05] [==========] 0 B/s        (0s) Downloaded /home/wfg/.cache/epkg/downloads/archlinux/core/os/x86_64/tzdata-2025b-1-x86_64.pkg.tar.zst
Installed packages saved to: /home/wfg/.epkg/envs/main/generations/2/installed-packages.json
Installation successful - Total packages: 6, AppBin packages: 1
AppBin package list: tree__2.2.1-1__x86_64
wfg /c/epkg% ~/.epkg/envs/main/usr/ebin/tree doc
error: can't open /lib64/ld-linux-x86-64.so.2

The actual archlinux dir layout is:

wfg /c/cci/design_meeting/epkg% podman run -it archlinux bash
[root@ab64f9e50743 /]# ls -l /
total 16
lrwxrwxrwx   1 root   root     7 Nov 21  2024 bin -> usr/bin
drwxr-xr-x   1 root   root     0 Nov 21  2024 boot
drwxr-xr-x   5 root   root   360 Jun  9 03:16 dev
drwxr-xr-x   1 root   root    38 Jun  9 03:16 etc
drwxr-xr-x   1 root   root     0 Nov 21  2024 home
lrwxrwxrwx   1 root   root     7 Nov 21  2024 lib -> usr/lib
lrwxrwxrwx   1 root   root     7 Nov 21  2024 lib64 -> usr/lib
drwxr-xr-x   1 root   root     0 Nov 21  2024 mnt
drwxr-xr-x   1 root   root     0 Nov 21  2024 opt
dr-xr-xr-x 615 nobody nobody   0 Jun  9 03:16 proc
drwxr-x---   1 root   root     0 Nov 21  2024 root
drwxr-xr-x   1 root   root    26 Jun  9 03:16 run
lrwxrwxrwx   1 root   root     7 Nov 21  2024 sbin -> usr/bin
drwxr-xr-x   1 root   root    14 Mar  2 00:03 srv
dr-xr-xr-x  13 nobody nobody   0 Jun  9 03:16 sys
drwxrwxrwt   1 root   root     0 Nov 21  2024 tmp
drwxr-xr-x   1 root   root    70 Mar  2 00:03 usr
drwxr-xr-x   1 root   root    10 Mar  2 00:03 var
[root@ab64f9e50743 /]# ls -l /usr/lib64
lrwxrwxrwx 1 root root 3 Nov 21  2024 /usr/lib64 -> lib
[root@ab64f9e50743 /]# ls -l /lib64
lrwxrwxrwx 1 root root 7 Nov 21  2024 /lib64 -> usr/lib

Signed-off-by: Wu Fengguang <wfg@mail.ustc.edu.cn>