epkg env create: make it work
wfg /c/epkg% RUST_BACKTRACE=1 /c/epkg/target/debug/epkg env create t2
Error: Failed to read file: /home/wfg/.epkg/config/envs/t2.yaml

Caused by:
    No such file or directory (os error 2)

Stack backtrace:
   2: epkg::io::<impl epkg::models::PackageManager>::get_env_config
             at ./src/io.rs:71:24
   3: epkg::dirs::<impl epkg::models::PackageManager>::get_env_root
             at ./src/dirs.rs:75:26
   4: epkg::dirs::<impl epkg::models::PackageManager>::get_generations_root
             at ./src/dirs.rs:84:24
   5: epkg::dirs::<impl epkg::models::PackageManager>::get_default_generations_root
             at ./src/dirs.rs:89:9
   6: epkg::history::<impl epkg::models::PackageManager>::get_current_generation_id
             at ./src/history.rs:12:32
   7: epkg::history::<impl epkg::models::PackageManager>::record_history
             at ./src/history.rs:75:30
   8: epkg::environment::<impl epkg::models::PackageManager>::create_environment_directories
             at ./src/environment.rs:226:9
   9: epkg::environment::<impl epkg::models::PackageManager>::create_environment
             at ./src/environment.rs:253:9
  10: epkg::<impl epkg::models::PackageManager>::command_env
             at ./src/main.rs:465:21

Signed-off-by: Wu Fengguang <wfg@mail.ustc.edu.cn>