epkg install: skip dir for create_ebin_wrappers()
wfg /c/epkg% RUST_BACKTRACE=1 target/debug/epkg install git
Warning: Some packages are already installed and will be skipped: (69 packages)
Error: Failed to install package rn31z9b7vdwwzj83nwdww41x2x376tyz__git__2.43.0__4.oe2403

Caused by:
    0: Failed to create ebin wrapper for /home/wfg/.epkg/store/rn31z9b7vdwwzj83nwdww41x2x376tyz__git__2.43.0__4.oe2403/fs/usr/libexec/git-core
    1: Is a directory (os error 21)

Signed-off-by: Wu Fengguang <wfg@mail.ustc.edu.cn>