install: remove py3compile symlink
Fixes:
["/home/wfg/.epkg/store/lsl4sc64f2ccp62cxfquizdaj5k4fpcu__python3-minimal__3.13.3-1__amd64/info/install/post_install.sh", "configure"]
Traceback (most recent call last):
  File "/usr/bin/py3compile", line 323, in <module>
    main()
    ~~~~^^
  File "/usr/bin/py3compile", line 284, in main
    pkg_files = tuple(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 55, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of python3-minimal

["/home/wfg/.epkg/store/fzmk6lodgsfftw6ppnjzbgzwu3prqkoq__python3__3.13.3-1__amd64/info/install/post_install.sh", "configure"]
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 209, in <module>
    main()
    ~~~~^^
  File "/usr/bin/py3clean", line 195, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 55, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of linux-perf

Root cause:
 51     process = Popen(('/usr/bin/dpkg', '-L', package_name), stdout=PIPE,
 52                          stderr=PIPE, env=env)
 53     stdout, stderr = process.communicate()
 54     if process.returncode != 0:
 55         raise Exception("cannot get content of %s" % package_name)

Signed-off-by: Wu Fengguang <wfg@mail.ustc.edu.cn>