epkg init: fixup runtime errors
- Add `DEFAULT_CHANNEL` and `DEFAULT_VERSION` constants
- Add `find_env_root(&str) -> Option<PathBuf>` to avoid egg-chicken problem
- Refactor environment creation and initialization logic in
  `environment.rs` and `init.rs` to use `find_env_root` and new helper
  methods for environment base path selection.
- Improve command-line option parsing in `main.rs`:
  - Use `.contains_id()` checks before accessing flags, avoid
    unconditional overriding config file setup
  - Set sensible defaults for version and channel, and ensure correct propagation of options

Fix errors like:

wfg /c/epkg% RUST_BACKTRACE=1 /c/epkg/target/debug/epkg init
Error: Failed to read file: /home/wfg/.epkg/config/envs/common.yaml

Caused by:
    No such file or directory (os error 2)

Stack backtrace:
   2: epkg::io::<impl epkg::models::PackageManager>::get_env_config
             at ./src/io.rs:71:24
   3: epkg::dirs::<impl epkg::models::PackageManager>::get_env_root
             at ./src/dirs.rs:75:26
   4: epkg::init::<impl epkg::models::PackageManager>::init
             at ./src/init.rs:22:13

Signed-off-by: Wu Fengguang <wfg@mail.ustc.edu.cn>