environment: symlink usr/sbin to bin on Fedora
On Fedora, /usr/sbin is a symlink to /usr/bin (unified bin and sbin
directories). Without this, scriptlets that call /usr/sbin/foo fail
because foo is actually in /usr/bin.

Fixes:
/home/wfg/.epkg/store/g4bd3koxrii7wtbnymdijzs3sfmfp3xg__filesystem__3.18-50.fc43__x86_64/info/install/post_trans.lua
/usr/sbin cannot be merged yet, /usr/sbin/addgroup points to /home/wfg/.epkg/envs/self/usr/bin/epkg

/home/wfg/.epkg/store/qmsdjtip7ofifjiexhicc4edw6nglhre__glibc__2.42-9.fc43__x86_64/info/install/post_install.lua
Error: call to /usr/sbin/iconvconfig failed.

Signed-off-by: Wu Fengguang <wfg@mail.ustc.edu.cn>