store: remove duplicate error context
Error: Failed to unpack package: /home/wfg/.cache/epkg/downloads/fedora/updates/42/Everything/x86_64/Packages/f/filesystem-3.18-42.fc42.x86_64.rpm

Caused by:
   0: Failed to unpack package /home/wfg/.cache/epkg/downloads/fedora/updates/42/Everything/x86_64/Packages/f/filesystem-3.18-42.fc42.x86_64.rpm to /home/wfg/.cache/epkg/unpack/818edc7a-0d92-4b94-9fbc-2691fc4cab62
   1: Failed to unpack RPM package /home/wfg/.cache/epkg/downloads/fedora/updates/42/Everything/x86_64/Packages/f/filesystem-3.18-42.fc42.x86_64.rpm to /home/wfg/.cache/epkg/unpack/818edc7a-0d92-4b94-9fbc-2691fc4cab62
   2: Permission denied (os error 13)

Location:
    src/rpm_pkg.rs:73:17

Signed-off-by: Wu Fengguang <wfg@mail.ustc.edu.cn>