epkg install: update current symlink as last step
To avoid current pointing to corrupt generation dir on failed install:

wfg /c/epkg% RUST_BACKTRACE=1 target/debug/epkg install git
Error: Failed to read file: /home/wfg/.epkg/envs/main/generations/3/installed-packages.json

Caused by:
    No such file or directory (os error 2)

Signed-off-by: Wu Fengguang <wfg@mail.ustc.edu.cn>